/**
 * lib/icons.ts
 * Central icon registry for RUNDA TSS Tech Club.
 * All icons come from lucide-react — one consistent, accessible, professional SVG set.
 *
 * Usage:
 *   import { Icons } from "@/lib/icons";
 *   <Icons.Check className="w-4 h-4" />
 *
 * Or import directly:
 *   import { BookOpen } from "lucide-react";
 */

export {
  // ─── Navigation & UI ─────────────────────────────────────────────────────
  ChevronDown,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  Menu,
  X,
  ExternalLink,
  MoreHorizontal,
  MoreVertical,

  // ─── Status & Feedback ───────────────────────────────────────────────────
  Check,
  CheckCircle,
  CheckCircle2,
  Circle,
  XCircle,
  AlertTriangle,
  AlertCircle,
  Info,
  Ban,
  ShieldCheck,
  ShieldAlert,
  Lock,
  Unlock,
  Clock,
  Timer,
  RefreshCw,
  Loader2,
  Flame,
  Zap,
  Star,
  Sparkles,
  Trophy,
  Medal,
  Award,

  // ─── Learning & Education ────────────────────────────────────────────────
  BookOpen,
  Book,
  BookMarked,
  GraduationCap,
  Pencil,
  PenLine,
  NotebookPen,
  Lightbulb,
  Brain,
  Target,
  Compass,
  FlaskConical,
  Microscope,
  Telescope,
  Calculator,
  BrainCircuit,

  // ─── Content Blocks ──────────────────────────────────────────────────────
  FileText,
  FileCode,
  FileQuestion,
  FileCheck,
  FileCheck2,
  FileBadge,
  FileVideo,
  FileImage,
  FileAudio,
  File,
  FilePlus,
  FileX,
  ClipboardList,
  ClipboardCheck,
  ListChecks,
  SquareCode,
  Code,
  Code2,
  Terminal,
  Hash,
  Type,
  Heading,
  Heading2,
  Heading3,
  AlignLeft,
  AlignCenter,
  AlignRight,
  AlignJustify,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Link,
  Link2,
  Image,
  ImagePlus,
  Play,
  Pause,
  Video,
  VideoOff,
  Volume2,
  VolumeX,
  Mic,
  MicOff,
  Paperclip,
  Upload,
  Download,
  Table,
  Columns,
  Quote,
  Minus,
  List,
  ListOrdered,
  Pilcrow,
  Scissors,
  Copy,
  ClipboardPaste,

  // ─── Quiz & Assessment ───────────────────────────────────────────────────
  CircleDot,
  ToggleLeft,
  Pen,
  LayoutList,
  ArrowUpDown,
  MessageSquare,
  MessagesSquare,
  Laptop,
  MonitorCheck,
  Brush,
  Headphones,
  Clapperboard,

  // ─── Users & Profile ─────────────────────────────────────────────────────
  User,
  User2,
  UserCircle,
  Users,
  UserCheck,
  UserPlus,
  UserCog,
  LogOut,
  LogIn,
  Camera,
  ScanFace,

  // ─── Admin & Settings ────────────────────────────────────────────────────
  Settings,
  Settings2,
  SlidersHorizontal,
  Shield,
  KeyRound,
  Eye,
  EyeOff,
  Search,
  Filter,
  SortAsc,
  SortDesc,

  // ─── Progress & Stats ────────────────────────────────────────────────────
  TrendingUp,
  TrendingDown,
  BarChart2,
  BarChart3,
  PieChart,
  Activity,
  Gauge,

  // ─── Communication ───────────────────────────────────────────────────────
  MessageCircle,
  Mail,
  Bell,
  BellRing,
  Send,
  Reply,
  Smile,
  Heart,
  ThumbsUp,
  Radio,
  Rss,

  // ─── Files & Storage ─────────────────────────────────────────────────────
  Folder,
  FolderOpen,
  FolderTree,
  Archive,
  Package,
  Database,
  HardDrive,
  Save,
  Inbox,

  // ─── Tech & Dev ──────────────────────────────────────────────────────────
  Globe,
  Globe2,
  Network,
  Server,
  ServerCog,
  Cpu,
  MemoryStick,
  Wifi,
  WifiOff,
  Plug,
  Github,
  GitBranch,
  GitCommit,
  Blocks,
  Binary,
  Braces,
  Bot,
  Smartphone,
  Monitor,
  Laptop2,
  Tablet,
  Cloud,
  CloudUpload,
  Workflow,
  Wrench,
  Cog,

  // ─── Actions ─────────────────────────────────────────────────────────────
  Plus,
  PlusCircle,
  Trash,
  Trash2,
  Edit,
  Edit2,
  Edit3,
  Move,
  MoveUp,
  MoveDown,
  RotateCcw,
  RotateCw,
  Maximize,
  Maximize2,
  Minimize,
  Minimize2,
  ZoomIn,
  ZoomOut,
  Expand,
  Shrink,
  Pin,
  Bookmark,
  Flag,
  Tag,
  Tags,

  // ─── Events & Calendar ───────────────────────────────────────────────────
  Calendar,
  CalendarDays,
  CalendarCheck,
  Clock3,
  Hourglass,
  SunMedium,
  PartyPopper,
  Users2,

  // ─── Layout & Misc ───────────────────────────────────────────────────────
  LayoutDashboard,
  LayoutGrid,
  Sidebar,
  SidebarOpen,
  SidebarClose,
  PanelLeft,
  PanelRight,
  Rows,
  Columns2,
  Layers,
  SeparatorHorizontal,
  Dot,
  Circle as CircleIcon,
  Square,
  Triangle,
  Hexagon,
  Infinity,
  MapPin,
  Navigation,
  Crosshair,

} from "lucide-react";


// ─── Named semantic aliases ────────────────────────────────────────────────
// Use these instead of thinking about which icon to pick each time.
import {
  CheckCircle2 as _CheckDone,
  AlertTriangle as _Warning,
  Info as _InfoIcon,
  Ban as _Error,
  Lightbulb as _Tip,
  BookOpen as _Lesson,
  GraduationCap as _Graduate,
  Target as _LearningOutcome,
  FolderOpen as _IndicativeContent,
  BookMarked as _Topic,
  ListChecks as _Item,
  FileText as _TextBlock,
  Code2 as _CodeBlock,
  ClipboardList as _QuizBlock,
  ListChecks as _ChecklistBlock,
  File as _DocumentBlock,
  Image as _ImageBlock,
  Video as _VideoBlock,
  Zap as _XP,
  Flame as _Streak,
  Trophy as _Challenge,
  Star as _Verified,
  BarChart2 as _Progress,
  Users as _Community,
  MessageCircle as _Chat,
  Send as _SendMessage,
  Paperclip as _Attach,
  Mic as _VoiceRecord,
  LogOut as _SignOut,
  UserCircle as _Profile,
  Settings as _Admin,
  Globe as _Online,
  WifiOff as _Offline,
} from "lucide-react";

export const Icons = {
  // Status
  CheckDone: _CheckDone,
  Warning: _Warning,
  InfoIcon: _InfoIcon,
  Error: _Error,
  Tip: _Tip,

  // Learning hierarchy
  LearningOutcome: _LearningOutcome,
  IndicativeContent: _IndicativeContent,
  Topic: _Topic,
  Item: _Item,

  // Block types
  TextBlock: _TextBlock,
  CodeBlock: _CodeBlock,
  QuizBlock: _QuizBlock,
  ChecklistBlock: _ChecklistBlock,
  DocumentBlock: _DocumentBlock,
  ImageBlock: _ImageBlock,
  VideoBlock: _VideoBlock,

  // Gamification
  XP: _XP,
  Streak: _Streak,
  Challenge: _Challenge,
  Verified: _Verified,
  Progress: _Progress,

  // App sections
  Lesson: _Lesson,
  Graduate: _Graduate,
  Community: _Community,
  Chat: _Chat,

  // Actions
  SendMessage: _SendMessage,
  Attach: _Attach,
  VoiceRecord: _VoiceRecord,
  SignOut: _SignOut,
  Profile: _Profile,
  Admin: _Admin,

  // Network
  Online: _Online,
  Offline: _Offline,
} as const;
