// ─── Static & Dynamic Curriculum Content for /learn/[moduleSlug] ─────────────
//
// Maps module slugs generated by scanCurriculum.ts to structured lesson content.
// Slugs follow: `${slugify(levelId)}-${slugify(trackFolderName)}-${slugify(fileBasename)}`
// ─────────────────────────────────────────────────────────────────────────────

export type TextBlock = { id: string; type: "text"; content: string };

export type Question = {
  id: string;
  questionType?:
  // Objective (auto-gradable)
  | "mcq"           // Multiple choice
  | "truefalse"     // True/False
  | "fillin"        // Fill in the blank
  | "matching"      // Match pairs
  | "ordering"      // Put items in correct order
  | "multiselect"   // Select all that apply
  // Subjective (requires manual grading)
  | "short"         // Short answer (1-3 sentences)
  | "essay"         // Long essay response
  | "coding"        // Code submission
  | "file_upload"   // Upload document/file
  | "drawing"       // Draw/diagram (image upload)
  | "audio"         // Audio response
  | "video";        // Video response

  question: string;              // Question text
  points?: number;               // Points worth (default: 1)
  rubric?: string;               // Grading rubric/guidelines for subjective questions

  // MCQ, multiselect
  options?: string[];
  correct?: number | number[];   // Single index or array of indices

  // Fill-in-the-blank
  blanks?: string[];             // Correct answers for each blank

  // Matching
  leftColumn?: string[];         // Items to match from
  rightColumn?: string[];        // Items to match to
  correctPairs?: Record<string, string>;  // Correct matches {left: right}

  // Ordering
  items?: string[];              // Items to put in order
  correctOrder?: number[];       // Correct sequence of indices

  // File uploads
  allowedFormats?: string[];     // e.g., ["pdf", "docx", "zip"]
  maxFileSize?: number;          // Max size in MB

  // Guidance
  sampleAnswer?: string;         // Model answer for reference
  explanation?: string;          // Explanation shown after grading
  hints?: string[];              // Optional hints
  timeLimit?: number;            // Time limit in seconds
};

export type QuizBlock = {
  id: string;
  type: "quiz";
  title?: string;          // Optional block title shown on pre-start screen
  questions: Question[];  // Multiple questions in one block
  // Legacy single-question fields (backward compat — still used in static content files)
  question?: string;
  options?: string[];
  correct?: number;
  blanks?: string[];
  sampleAnswer?: string;
  explanation?: string;
};

export type ChecklistBlock = { id: string; type: "checklist"; items: string[] };
export type CodeBlock = { id: string; type: "code"; language: string; code: string; caption?: string };
export type DocumentBlock = { id: string; type: "document"; url: string; title: string; fileType?: string; description?: string };
export type ImageBlock = { id: string; type: "image"; url: string; caption?: string; alt?: string };
export type VideoBlock = { id: string; type: "video"; url: string; title?: string; description?: string };
export type LearnBlock = TextBlock | QuizBlock | ChecklistBlock | CodeBlock | DocumentBlock | ImageBlock | VideoBlock;

export type LearnTopic = {
  id: string;
  title: string;
  description?: string;
  items?: string[]; // Curriculum items for 4th level display
  blocks: LearnBlock[];
};

export type IndicativeContent = {
  id: string;
  title: string;
  topics: LearnTopic[];
};

export type LearningOutcome = {
  number: number;
  title: string;
  learningHours: number;
  indicativeContents: IndicativeContent[];
};

export type LearnModule = {
  slug: string;
  moduleCode: string;
  title: string;
  tier: string;         // "l3" | "l4" | "l5"
  trackName: string;    // matches DB SkillTrack name
  xpReward: number;
  estimatedMinutes: number;
  description: string;
  outcomes: LearningOutcome[];
};

// ─── Module Registry (to be populated below) ───────────────────────────────────

const MODULES: LearnModule[] = [];

// ─── SWDBD401 — Backend Application Development ───────────────────────────────

const swdbd401: LearnModule = {
  slug: "l4-specific-modules-swdbd401-backend-application-development",
  moduleCode: "SWDBD401",
  title: "Backend Application Development",
  tier: "l4",
  trackName: "L4 — Specific Modules",
  xpReward: 100,
  estimatedMinutes: 300,
  description: "Develop a Backend Application using Node.js. This module covers RESTful APIs, security, testing, and deployment.",
  outcomes: [
    {
      number: 1,
      title: "Develop RESTFUL APIs with Node JS",
      learningHours: 45,
      indicativeContents: [
        {
          id: "swdbd401-lo1-ic1",
          title: "Setup Node.js Environment",
          topics: [
            {
              id: "swdbd401-lo1-ic1-t1",
              title: "Description of Node.js Key Concepts",
              blocks: [
                {
                  id: "swdbd401-lo1-ic1-t1-text1",
                  type: "text",
                  content: `## Node.js Key Concepts

**Node.js** is a JavaScript runtime built on Chrome's V8 engine, enabling server-side JavaScript execution.

### Key Concepts:
- **Node.js**: Server-side JavaScript runtime
- **NPM (Node Package Manager)**: Package manager for Node.js
- **Express.js**: Minimal web framework for Node.js
- **Routes**: URL endpoints that map to specific functions
- **APIs (Application Programming Interfaces)**: Communication protocols between systems
- **Backend Application**: Server-side logic and data management
- **Dependencies**: External libraries your project relies on
- **Postman**: API testing tool
- **Nodemon**: Development tool that auto-restarts server on file changes
- **DBMS**: Database Management System (SQL: MySQL, PostgreSQL; NoSQL: MongoDB)`
                },
                {
                  id: "swdbd401-lo1-ic1-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo1-ic1-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "What is Node.js primarily used for?",
                    options: [
                      "Client-side animations",
                      "Server-side JavaScript execution",
                      "Database management",
                      "CSS styling"
                    ],
                    correct: 1,
                    explanation: "Node.js is a runtime that allows JavaScript to run on the server side, outside the browser."
                  }],
                }
              ]
            },
            {
              id: "swdbd401-lo1-ic1-t2",
              title: "Installation of Node.js Modules and Packages",
              blocks: [
                {
                  id: "swdbd401-lo1-ic1-t2-text1",
                  type: "text",
                  content: `## Installing Node.js Environment

### Installation Steps:
1. **Install Node.js and NPM**: Download from [nodejs.org](https://nodejs.org)
2. **Verify Installation**:
\`\`\`bash
node --version
npm --version
\`\`\`
3. **Install Express.js**:
\`\`\`bash
npm install express
\`\`\`
4. **Install Nodemon (dev tool)**:
\`\`\`bash
npm install --save-dev nodemon
\`\`\`
5. **Install Postman**: Download from [postman.com](https://www.postman.com)`
                },
                {
                  id: "swdbd401-lo1-ic1-t2-code1",
                  type: "code",
                  language: "json",
                  caption: "Example package.json with dependencies",
                  code: `{
  "name": "backend-api",
  "version": "1.0.0",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "express": "^4.18.2",
    "mysql2": "^3.6.0"
  },
  "devDependencies": {
    "nodemon": "^3.0.1"
  }
}`
                },
                {
                  id: "swdbd401-lo1-ic1-t2-chk1",
                  type: "checklist",
                  items: [
                    "I have installed Node.js and NPM on my system",
                    "I have created a package.json file",
                    "I have installed Express.js and Nodemon"
                  ]
                }
              ]
            },
            {
              id: "swdbd401-lo1-ic1-t3",
              title: "Configuration of MySQL Server",
              blocks: [
                {
                  id: "swdbd401-lo1-ic1-t3-text1",
                  type: "text",
                  content: `## MySQL Server Setup

### Steps:
1. **Install MySQL Server**: Download MySQL Community Server
2. **Install MySQL Workbench**: GUI tool for database management
3. **Create a Database**:
\`\`\`sql
CREATE DATABASE backend_db;
USE backend_db;
\`\`\`
4. **Configure Connection**: Note your host, port, username, and password`
                },
                {
                  id: "swdbd401-lo1-ic1-t3-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo1-ic1-t3-quiz1-q1",
                    questionType: "mcq",
                    question: "What is MySQL Workbench used for?",
                    options: [
                      "Writing Node.js code",
                      "Managing and visualizing MySQL databases",
                      "Testing APIs",
                      "Version control"
                    ],
                    correct: 1,
                    explanation: "MySQL Workbench is a GUI tool for designing, managing, and querying MySQL databases."
                  }],
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo1-ic2",
          title: "Connection of Node.js to the ES5 or ES6 Server",
          topics: [
            {
              id: "swdbd401-lo1-ic2-t1",
              title: "Creation of Basic Server with Express.js",
              blocks: [
                {
                  id: "swdbd401-lo1-ic2-t1-text1",
                  type: "text",
                  content: `## Creating a Basic Express Server

Express.js provides a simple way to create HTTP servers in Node.js.`
                },
                {
                  id: "swdbd401-lo1-ic2-t1-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Basic Express server - server.js",
                  code: `const express = require('express');
const app = express();
const PORT = 3000;

// Middleware to parse JSON bodies
app.use(express.json());

// Basic route
app.get('/', (req, res) => {
  res.json({ message: 'Welcome to Backend API' });
});

// Health check endpoint
app.get('/api/health', (req, res) => {
  res.json({ status: 'OK', timestamp: new Date() });
});

app.listen(PORT, () => {
  console.log(\`Server running on http://localhost:\${PORT}\`);
});`
                },
                {
                  id: "swdbd401-lo1-ic2-t1-chk1",
                  type: "checklist",
                  items: [
                    "I have created a basic Express server",
                    "I can start the server and access it via browser",
                    "I understand middleware and routes"
                  ]
                }
              ]
            },
            {
              id: "swdbd401-lo1-ic2-t2",
              title: "Application of Client Libraries (HTTP, HTTPS, Axios, Request)",
              blocks: [
                {
                  id: "swdbd401-lo1-ic2-t2-text1",
                  type: "text",
                  content: `## Client Libraries for HTTP Communication

Node.js provides multiple ways to make HTTP requests:

| Library | Description |
|---------|-------------|
| **http/https** | Built-in Node.js modules for making requests |
| **Axios** | Promise-based HTTP client, most popular |
| **Request** | Simple HTTP request library (deprecated but widely used) |

### Install Axios:
\`\`\`bash
npm install axios
\`\`\``
                },
                {
                  id: "swdbd401-lo1-ic2-t2-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Making HTTP requests with Axios",
                  code: `const axios = require('axios');

// GET request
async function fetchData() {
  try {
    const response = await axios.get('https://api.example.com/data');
    console.log(response.data);
  } catch (error) {
    console.error('Error:', error.message);
  }
}

// POST request
async function sendData(payload) {
  const response = await axios.post('https://api.example.com/items', payload);
  return response.data;
}`
                },
                {
                  id: "swdbd401-lo1-ic2-t2-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo1-ic2-t2-quiz1-q1",
                    questionType: "mcq",
                    question: "Which library is the most popular promise-based HTTP client for Node.js?",
                    options: ["http (built-in)", "Request", "Axios", "fetch"],
                    correct: 2,
                    explanation: "Axios is the most widely used promise-based HTTP client for Node.js, supporting async/await syntax."
                  }],
                }
              ]
            },
            {
              id: "swdbd401-lo1-ic2-t3",
              title: "Establishment and Testing of Server Connection",
              blocks: [
                {
                  id: "swdbd401-lo1-ic2-t3-text1",
                  type: "text",
                  content: `## Setting Up and Testing Server Connection

### Connection Steps:
1. **Setup connection parameters** (host, port, credentials)
2. **Create / send a request** using a HTTP method
3. **Handle the response** — success or error
4. **Test with Postman** — send GET request to your server URL`
                },
                {
                  id: "swdbd401-lo1-ic2-t3-chk1",
                  type: "checklist",
                  items: [
                    "I can establish a server connection",
                    "I can send HTTP requests and handle responses",
                    "I can test my server endpoints with Postman"
                  ]
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo1-ic3",
          title: "Establishment of Database Connection",
          topics: [
            {
              id: "swdbd401-lo1-ic3-t1",
              title: "Create Database and Schema Setup",
              blocks: [
                {
                  id: "swdbd401-lo1-ic3-t1-code1",
                  type: "code",
                  language: "sql",
                  caption: "Create and setup database schema",
                  code: `-- Create Database
CREATE DATABASE IF NOT EXISTS backend_db;
USE backend_db;

-- Create a sample table
CREATE TABLE products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  quantity INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);`
                },
                {
                  id: "swdbd401-lo1-ic3-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo1-ic3-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "Which SQL statement is used to create a new table?",
                    options: ["INSERT TABLE", "CREATE TABLE", "MAKE TABLE", "ADD TABLE"],
                    correct: 1,
                    explanation: "CREATE TABLE is the SQL statement used to create a new table in a database."
                  }],
                }
              ]
            },
            {
              id: "swdbd401-lo1-ic3-t2",
              title: "Configure and Test Database Connection in Node.js",
              blocks: [
                {
                  id: "swdbd401-lo1-ic3-t2-code1",
                  type: "code",
                  language: "javascript",
                  caption: "MySQL connection using mysql2",
                  code: `const mysql = require('mysql2');

// Create connection pool
const pool = mysql.createPool({
  host: process.env.DB_HOST || 'localhost',
  user: process.env.DB_USER || 'root',
  password: process.env.DB_PASS,
  database: process.env.DB_NAME || 'backend_db',
  waitForConnections: true,
  connectionLimit: 10,
});

// Test connection
pool.getConnection((err, connection) => {
  if (err) {
    console.error('Database connection failed:', err);
    return;
  }
  console.log('Database connected successfully!');
  connection.release();
});

module.exports = pool.promise();`
                },
                {
                  id: "swdbd401-lo1-ic3-t2-chk1",
                  type: "checklist",
                  items: [
                    "I have installed the mysql2 package",
                    "I have set up environment variables for DB credentials",
                    "I have tested the database connection successfully"
                  ]
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo1-ic4",
          title: "Develop RESTFUL APIs",
          topics: [
            {
              id: "swdbd401-lo1-ic4-t1",
              title: "Define Endpoints and HTTP Methods",
              blocks: [
                {
                  id: "swdbd401-lo1-ic4-t1-text1",
                  type: "text",
                  content: `## RESTful API Endpoints & HTTP Methods

A RESTful API uses standard HTTP methods to perform CRUD operations:

| HTTP Method | CRUD Operation | Example Endpoint |
|-------------|---------------|-----------------|
| **GET** | Read | GET /api/products |
| **POST** | Create | POST /api/products |
| **PUT** | Update | PUT /api/products/:id |
| **DELETE** | Delete | DELETE /api/products/:id |`
                },
                {
                  id: "swdbd401-lo1-ic4-t1-code1",
                  type: "code",
                  language: "javascript",
                  caption: "All CRUD endpoints for products",
                  code: `const express = require('express');
const router = express.Router();
const db = require('./db');

// GET all items
router.get('/', async (req, res) => {
  const [rows] = await db.query('SELECT * FROM products');
  res.json(rows);
});

// GET specific item by ID
router.get('/:id', async (req, res) => {
  const [rows] = await db.query('SELECT * FROM products WHERE id = ?', [req.params.id]);
  if (!rows.length) return res.status(404).json({ error: 'Not found' });
  res.json(rows[0]);
});

// POST create item
router.post('/', async (req, res) => {
  const { name, price, quantity } = req.body;
  const [result] = await db.query(
    'INSERT INTO products (name, price, quantity) VALUES (?, ?, ?)',
    [name, price, quantity]
  );
  res.status(201).json({ id: result.insertId, name, price, quantity });
});

// PUT update item
router.put('/:id', async (req, res) => {
  const { name, price, quantity } = req.body;
  await db.query(
    'UPDATE products SET name=?, price=?, quantity=? WHERE id=?',
    [name, price, quantity, req.params.id]
  );
  res.json({ message: 'Product updated' });
});

// DELETE remove item
router.delete('/:id', async (req, res) => {
  await db.query('DELETE FROM products WHERE id = ?', [req.params.id]);
  res.json({ message: 'Product deleted' });
});

module.exports = router;`
                },
                {
                  id: "swdbd401-lo1-ic4-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo1-ic4-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "Which HTTP method should be used to update an existing resource?",
                    options: ["GET", "POST", "PUT", "DELETE"],
                    correct: 2,
                    explanation: "PUT is used to update/replace an existing resource. PATCH is also acceptable for partial updates."
                  }],
                }
              ]
            },
            {
              id: "swdbd401-lo1-ic4-t2",
              title: "Middleware Services (Error Handling, Logging, Validation)",
              blocks: [
                {
                  id: "swdbd401-lo1-ic4-t2-text1",
                  type: "text",
                  content: `## Middleware in Express.js

Middleware functions execute during the request-response cycle. Types:
- **Application-level middleware**: Runs for all routes
- **Router-level middleware**: Runs for specific routers
- **Error-handling middleware**: Has (err, req, res, next) signature
- **Built-in middleware**: \`express.json()\`, \`express.static()\`
- **Third-party middleware**: Morgan (logging), Joi (validation)`
                },
                {
                  id: "swdbd401-lo1-ic4-t2-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Middleware for logging, validation, and error handling",
                  code: `const express = require('express');
const app = express();

// Logging middleware
app.use((req, res, next) => {
  console.log(\`[\${new Date().toISOString()}] \${req.method} \${req.url}\`);
  next();
});

// Input validation middleware
function validateProduct(req, res, next) {
  const { name, price } = req.body;
  if (!name || !price) {
    return res.status(400).json({ error: 'name and price are required' });
  }
  next();
}

// Error-handling middleware (must have 4 params)
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({ error: 'Internal Server Error' });
});`
                },
                {
                  id: "swdbd401-lo1-ic4-t2-chk1",
                  type: "checklist",
                  items: [
                    "I understand what middleware is and when to use it",
                    "I have implemented request logging",
                    "I have implemented input validation",
                    "I have implemented centralized error handling"
                  ]
                }
              ]
            },
            {
              id: "swdbd401-lo1-ic4-t3",
              title: "HTTP Status Codes and Debugging APIs",
              blocks: [
                {
                  id: "swdbd401-lo1-ic4-t3-text1",
                  type: "text",
                  content: `## HTTP Status Codes

| Code | Meaning | When to use |
|------|---------|------------|
| **200** | OK | Successful GET/PUT |
| **201** | Created | Successful POST |
| **204** | No Content | Successful DELETE |
| **400** | Bad Request | Invalid input |
| **401** | Unauthorized | Missing/invalid auth |
| **403** | Forbidden | Not allowed |
| **404** | Not Found | Resource not found |
| **500** | Server Error | Unexpected server error |`
                },
                {
                  id: "swdbd401-lo1-ic4-t3-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo1-ic4-t3-quiz1-q1",
                    questionType: "mcq",
                    question: "What HTTP status code should you return when a resource is successfully created?",
                    options: ["200 OK", "201 Created", "204 No Content", "400 Bad Request"],
                    correct: 1,
                    explanation: "201 Created is the correct status code for a successful POST request that creates a new resource."
                  }],
                }
              ]
            }
          ]
        }
      ]
    },

    {
      number: 2,
      title: "Secure Backend Application",
      learningHours: 20,
      indicativeContents: [
        {
          id: "swdbd401-lo2-ic1",
          title: "Data Encryption in Securing RESTFUL APIs",
          topics: [
            {
              id: "swdbd401-lo2-ic1-t1",
              title: "Introduction to Data Encryption",
              blocks: [
                {
                  id: "swdbd401-lo2-ic1-t1-text1",
                  type: "text",
                  content: `## Data Encryption in RESTful APIs

**Encryption** converts data into an unreadable format to protect it from unauthorized access.

### Types of Data Encryption:
- **Symmetric Encryption**: Same key for encryption and decryption (AES)
- **Asymmetric Encryption**: Public key encrypts, private key decrypts (RSA)
- **Hashing**: One-way transformation (bcrypt for passwords)

### Benefits:
- Protects sensitive data at rest and in transit
- Meets compliance requirements (GDPR, HIPAA)
- Prevents data theft if database is compromised`
                },
                {
                  id: "swdbd401-lo2-ic1-t1-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Encrypting data using Node.js crypto module",
                  code: `const crypto = require('crypto');

const ALGORITHM = 'aes-256-cbc';
const KEY = crypto.randomBytes(32); // 256-bit key
const IV = crypto.randomBytes(16);  // initialization vector

// Encrypt
function encrypt(text) {
  const cipher = crypto.createCipheriv(ALGORITHM, KEY, IV);
  let encrypted = cipher.update(text, 'utf8', 'hex');
  encrypted += cipher.final('hex');
  return { encrypted, iv: IV.toString('hex') };
}

// Decrypt
function decrypt(encryptedData, iv) {
  const decipher = crypto.createDecipheriv(ALGORITHM, KEY, Buffer.from(iv, 'hex'));
  let decrypted = decipher.update(encryptedData, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}

const { encrypted, iv } = encrypt('Sensitive Data');
console.log('Encrypted:', encrypted);
console.log('Decrypted:', decrypt(encrypted, iv));`
                },
                {
                  id: "swdbd401-lo2-ic1-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo2-ic1-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "Which hashing algorithm is recommended for storing passwords?",
                    options: ["MD5", "SHA-1", "bcrypt", "AES-256"],
                    correct: 2,
                    explanation: "bcrypt is specifically designed for password hashing — it includes a salt and is computationally slow, making brute-force attacks impractical."
                  }],
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo2-ic2",
          title: "Integrating and Using Third-Party Libraries",
          topics: [
            {
              id: "swdbd401-lo2-ic2-t1",
              title: "Installing and Using Common Node.js Libraries",
              blocks: [
                {
                  id: "swdbd401-lo2-ic2-t1-text1",
                  type: "text",
                  content: `## Common Node.js Third-Party Libraries

| Library | Purpose |
|---------|---------|
| **Express** | Web framework |
| **Lodash** | Utility functions |
| **Moment.js** | Date/time manipulation |
| **Joi** | Data validation |
| **bcrypt** | Password hashing |`
                },
                {
                  id: "swdbd401-lo2-ic2-t1-text2",
                  type: "text",
                  content: `### Async Patterns with Third-Party Libraries:
- **Callbacks**: Traditional Node.js pattern
- **Promises**: \`.then().catch()\` chain
- **async/await**: Modern, cleaner syntax (preferred)`
                },
                {
                  id: "swdbd401-lo2-ic2-t1-chk1",
                  type: "checklist",
                  items: [
                    "I can install packages using npm install",
                    "I understand callbacks, Promises, and async/await",
                    "I can integrate third-party libraries in my project"
                  ]
                }
              ]
            },
            {
              id: "swdbd401-lo2-ic2-t2",
              title: "Maintaining and Updating Third-Party Libraries",
              blocks: [
                {
                  id: "swdbd401-lo2-ic2-t2-code1",
                  type: "code",
                  language: "bash",
                  caption: "Checking and updating library dependencies",
                  code: `# Check for outdated packages
npm outdated

# Check for security vulnerabilities
npm audit

# Fix vulnerabilities automatically
npm audit fix

# Update a specific package
npm update express

# Check versions in package.json and package-lock.json`
                },
                {
                  id: "swdbd401-lo2-ic2-t2-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo2-ic2-t2-quiz1-q1",
                    questionType: "mcq",
                    question: "Which tool detects security vulnerabilities in npm packages?",
                    options: ["npm outdated", "npm audit", "npm install", "npm test"],
                    correct: 1,
                    explanation: "npm audit scans your dependencies for known security vulnerabilities and reports them."
                  }],
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo2-ic3",
          title: "Implementation of Authentication, Authorization & Accountability (AAA)",
          topics: [
            {
              id: "swdbd401-lo2-ic3-t1",
              title: "Authentication with JWT and Passport",
              blocks: [
                {
                  id: "swdbd401-lo2-ic3-t1-text1",
                  type: "text",
                  content: `## Authentication in Node.js

**Authentication** verifies who the user is.

### Frameworks:
- **Passport.js**: Flexible authentication middleware
- **JWT (JSON Web Tokens)**: Stateless token-based authentication
- **Social Auth**: Google, Facebook OAuth`
                },
                {
                  id: "swdbd401-lo2-ic3-t1-code1",
                  type: "code",
                  language: "javascript",
                  caption: "JWT Authentication implementation",
                  code: `const jwt = require('jsonwebtoken');
const bcrypt = require('bcrypt');

const SECRET = process.env.JWT_SECRET;

// Login endpoint — generates JWT
app.post('/api/login', async (req, res) => {
  const { email, password } = req.body;
  const user = await findUserByEmail(email);
  if (!user) return res.status(401).json({ error: 'Invalid credentials' });

  const valid = await bcrypt.compare(password, user.passwordHash);
  if (!valid) return res.status(401).json({ error: 'Invalid credentials' });

  const token = jwt.sign({ userId: user.id, role: user.role }, SECRET, { expiresIn: '24h' });
  res.json({ token });
});

// Middleware to protect routes
function requireAuth(req, res, next) {
  const token = req.headers.authorization?.split(' ')[1];
  if (!token) return res.status(401).json({ error: 'No token provided' });
  try {
    req.user = jwt.verify(token, SECRET);
    next();
  } catch {
    res.status(401).json({ error: 'Invalid token' });
  }
}`
                },
                {
                  id: "swdbd401-lo2-ic3-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo2-ic3-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "What does JWT stand for?",
                    options: ["Java Web Token", "JSON Web Token", "JavaScript Web Transfer", "JSON Web Transport"],
                    correct: 1,
                    explanation: "JWT stands for JSON Web Token — a compact, URL-safe token for securely transmitting claims between parties."
                  }],
                }
              ]
            },
            {
              id: "swdbd401-lo2-ic3-t2",
              title: "Authorization — Role-Based Access Control",
              blocks: [
                {
                  id: "swdbd401-lo2-ic3-t2-text1",
                  type: "text",
                  content: `## Authorization — Who Can Do What

**Authorization** determines what an authenticated user is allowed to do.

### Role-Based Access Control (RBAC):
- Assign roles to users (admin, user, manager)
- Each role has specific permissions
- Check role before allowing access to a resource`
                },
                {
                  id: "swdbd401-lo2-ic3-t2-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Role-based authorization middleware",
                  code: `// Role-based authorization middleware
function requireRole(...roles) {
  return (req, res, next) => {
    if (!req.user) return res.status(401).json({ error: 'Not authenticated' });
    if (!roles.includes(req.user.role)) {
      return res.status(403).json({ error: 'Forbidden — insufficient permissions' });
    }
    next();
  };
}

// Usage: only admins can delete products
app.delete('/api/products/:id', requireAuth, requireRole('admin'), async (req, res) => {
  await db.query('DELETE FROM products WHERE id = ?', [req.params.id]);
  res.json({ message: 'Deleted' });
});`
                },
                {
                  id: "swdbd401-lo2-ic3-t2-chk1",
                  type: "checklist",
                  items: [
                    "I understand the difference between authentication and authorization",
                    "I can implement JWT-based authentication",
                    "I can implement role-based access control",
                    "I can implement request logging with Winston or Morgan"
                  ]
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo2-ic4",
          title: "Secure Environment Variables",
          topics: [
            {
              id: "swdbd401-lo2-ic4-t1",
              title: "Managing Environment Variables with dotenv",
              blocks: [
                {
                  id: "swdbd401-lo2-ic4-t1-text1",
                  type: "text",
                  content: `## Environment Variables Security

Environment variables store sensitive configuration outside code:
- Database credentials
- API keys
- JWT secrets
- Encryption keys

### Best Practices:
- Never commit \`.env\` to version control (add to \`.gitignore\`)
- Use a key management service in production
- Rotate keys regularly`
                },
                {
                  id: "swdbd401-lo2-ic4-t1-code1",
                  type: "code",
                  language: "bash",
                  caption: ".env file example",
                  code: `# .env (NEVER commit this file)
DB_HOST=localhost
DB_USER=root
DB_PASS=your_secure_password
DB_NAME=backend_db
JWT_SECRET=your_super_secret_jwt_key_here
PORT=3000`
                },
                {
                  id: "swdbd401-lo2-ic4-t1-code2",
                  type: "code",
                  language: "javascript",
                  caption: "Loading env vars with dotenv",
                  code: `// At the top of your main file
require('dotenv').config();

const dbConfig = {
  host: process.env.DB_HOST,
  user: process.env.DB_USER,
  password: process.env.DB_PASS,
  database: process.env.DB_NAME,
};`
                },
                {
                  id: "swdbd401-lo2-ic4-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo2-ic4-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "Where should you NOT store sensitive API keys and database passwords?",
                    options: [
                      "In environment variables",
                      "Directly in your source code committed to Git",
                      "In a .env file (not committed)",
                      "In a secret management service"
                    ],
                    correct: 1,
                    explanation: "Never hardcode secrets directly in source code that gets committed to Git — they become permanently visible in version history."
                  }],
                }
              ]
            }
          ]
        }
      ]
    },
    {
      number: 3,
      title: "Test Backend Application",
      learningHours: 20,
      indicativeContents: [
        {
          id: "swdbd401-lo3-ic1",
          title: "Unit Testing",
          topics: [
            {
              id: "swdbd401-lo3-ic1-t1",
              title: "Unit Testing with Mocha and Chai",
              blocks: [
                {
                  id: "swdbd401-lo3-ic1-t1-text1",
                  type: "text",
                  content: `## Unit Testing in Node.js

**Unit testing** verifies individual functions/modules work correctly in isolation.

### Tools:
- **Mocha**: Test runner framework
- **Chai**: Assertion library
- **Jest**: All-in-one testing framework (popular alternative)
- **Supertest**: HTTP endpoint testing`
                },
                {
                  id: "swdbd401-lo3-ic1-t1-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Unit test with Mocha and Chai",
                  code: `const { expect } = require('chai');
const { calculateTotal } = require('../utils/calculator');

describe('Calculator Utils', () => {
  it('should calculate total price correctly', () => {
    const items = [
      { price: 1000, quantity: 2 },
      { price: 500, quantity: 3 },
    ];
    const total = calculateTotal(items);
    expect(total).to.equal(3500);
  });

  it('should return 0 for empty cart', () => {
    expect(calculateTotal([])).to.equal(0);
  });
});`
                },
                {
                  id: "swdbd401-lo3-ic1-t1-code2",
                  type: "code",
                  language: "javascript",
                  caption: "Testing API endpoints with Supertest",
                  code: `const request = require('supertest');
const app = require('../app');

describe('Products API', () => {
  it('GET /api/products should return 200', async () => {
    const res = await request(app).get('/api/products');
    expect(res.statusCode).toBe(200);
    expect(res.body).toBeInstanceOf(Array);
  });

  it('POST /api/products should create a product', async () => {
    const res = await request(app)
      .post('/api/products')
      .send({ name: 'Test Product', price: 500, quantity: 10 });
    expect(res.statusCode).toBe(201);
    expect(res.body.name).toBe('Test Product');
  });
});`
                },
                {
                  id: "swdbd401-lo3-ic1-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo3-ic1-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "What is the primary purpose of unit testing?",
                    options: [
                      "Testing the full user workflow end-to-end",
                      "Testing individual functions in isolation",
                      "Testing server deployment",
                      "Testing UI components"
                    ],
                    correct: 1,
                    explanation: "Unit testing focuses on testing individual functions or modules in isolation to verify they produce the correct output."
                  }],
                },
                {
                  id: "swdbd401-lo3-ic1-t1-chk1",
                  type: "checklist",
                  items: [
                    "I have installed Mocha/Jest and Chai",
                    "I can write basic unit tests for functions",
                    "I can test API endpoints with Supertest"
                  ]
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo3-ic2",
          title: "Usability Testing",
          topics: [
            {
              id: "swdbd401-lo3-ic2-t1",
              title: "Usability Testing According to Expected Results",
              blocks: [
                {
                  id: "swdbd401-lo3-ic2-t1-text1",
                  type: "text",
                  content: `## Usability Testing

**Usability testing** checks that the API behaves as expected from the user's perspective.

### What to Test:
- All endpoints return correct status codes
- Response format matches API documentation
- Error messages are clear and helpful
- Pagination and filtering work correctly
- All required fields are validated

### Tools:
- **Postman Collections**: Automate API testing sequences
- **Swagger/OpenAPI**: Document and test endpoints interactively
- **Newman**: Run Postman collections from command line`
                },
                {
                  id: "swdbd401-lo3-ic2-t1-chk1",
                  type: "checklist",
                  items: [
                    "I have tested all endpoints with Postman",
                    "I have documented expected inputs and outputs",
                    "I have verified error responses are user-friendly"
                  ]
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo3-ic3",
          title: "Security Testing",
          topics: [
            {
              id: "swdbd401-lo3-ic3-t1",
              title: "Security Testing Based on System Threats",
              blocks: [
                {
                  id: "swdbd401-lo3-ic3-t1-text1",
                  type: "text",
                  content: `## Security Testing

**Security testing** identifies vulnerabilities that could be exploited.

### Common Threats to Test:
- **SQL Injection**: Malicious SQL in inputs — use parameterized queries
- **XSS (Cross-Site Scripting)**: Script injection — sanitize inputs
- **CSRF**: Cross-site request forgery — use CSRF tokens
- **Brute Force**: Too many login attempts — implement rate limiting
- **Insecure Dependencies**: Use \`npm audit\` regularly

### Tools:
- **OWASP ZAP**: Automated security scanner
- **Snyk**: Dependency vulnerability scanner
- **helmet.js**: Sets secure HTTP headers in Express`
                },
                {
                  id: "swdbd401-lo3-ic3-t1-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Securing Express with Helmet and rate limiting",
                  code: `const helmet = require('helmet');
const rateLimit = require('express-rate-limit');

// Security headers
app.use(helmet());

// Rate limiting — max 100 requests per 15 min per IP
const limiter = rateLimit({
  windowMs: 15 * 60 * 1000,
  max: 100,
  message: { error: 'Too many requests, please try again later.' }
});
app.use('/api', limiter);`
                },
                {
                  id: "swdbd401-lo3-ic3-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo3-ic3-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "What type of attack does parameterized SQL queries prevent?",
                    options: ["XSS", "SQL Injection", "CSRF", "Brute Force"],
                    correct: 1,
                    explanation: "Parameterized queries (prepared statements) prevent SQL Injection by separating SQL code from user-supplied data."
                  }],
                }
              ]
            }
          ]
        }
      ]
    },
    {
      number: 4,
      title: "Manage Backend Application",
      learningHours: 15,
      indicativeContents: [
        {
          id: "swdbd401-lo4-ic1",
          title: "Application Deployment",
          topics: [
            {
              id: "swdbd401-lo4-ic1-t1",
              title: "Deploying Node.js Application (FURPS Requirements)",
              blocks: [
                {
                  id: "swdbd401-lo4-ic1-t1-text1",
                  type: "text",
                  content: `## Deploying a Node.js Backend

**FURPS** quality requirements: Functionality, Usability, Reliability, Performance, Supportability.

### Deployment Platforms:
| Platform | Description |
|----------|-------------|
| **Firebase** | Google's hosting — good for Node.js APIs |
| **Heroku** | Simple PaaS deployment |
| **AWS Lambda** | Serverless Node.js |
| **Railway / Render** | Modern easy deployment |
| **PM2** | Process manager for production Node.js |

### Steps to Deploy:
1. Prepare production environment variables
2. Run \`npm run build\` (if needed)
3. Push code to the platform
4. Configure environment variables on the server
5. Monitor with PM2 or platform dashboard`
                },
                {
                  id: "swdbd401-lo4-ic1-t1-code1",
                  type: "code",
                  language: "bash",
                  caption: "Using PM2 for production process management",
                  code: `# Install PM2 globally
npm install -g pm2

# Start your app with PM2
pm2 start server.js --name "backend-api"

# Monitor processes
pm2 monit

# Auto-restart on server reboot
pm2 startup
pm2 save

# View logs
pm2 logs backend-api`
                },
                {
                  id: "swdbd401-lo4-ic1-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo4-ic1-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "What is PM2 used for?",
                    options: [
                      "Database management",
                      "Process management for Node.js in production",
                      "Package installation",
                      "Writing unit tests"
                    ],
                    correct: 1,
                    explanation: "PM2 is a production process manager for Node.js that handles auto-restart, monitoring, log management, and clustering."
                  }],
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo4-ic2",
          title: "Backend Maintenance",
          topics: [
            {
              id: "swdbd401-lo4-ic2-t1",
              title: "Maintaining Backend According to System Functionalities",
              blocks: [
                {
                  id: "swdbd401-lo4-ic2-t1-text1",
                  type: "text",
                  content: `## Backend Application Maintenance

### Key Maintenance Tasks:
- **Monitor performance**: CPU, memory, response times
- **Update dependencies**: Regularly run \`npm audit\` and \`npm update\`
- **Database optimization**: Index frequently queried columns, analyze slow queries
- **Log management**: Rotate logs, monitor for errors
- **Backup strategy**: Regular database backups
- **Redis caching**: Cache frequent DB queries to improve performance

### Tools:
- **Winston/Morgan**: Structured logging
- **PM2**: Process monitoring
- **Redis**: In-memory caching
- **MySQL slow query log**: Identify slow queries`
                },
                {
                  id: "swdbd401-lo4-ic2-t1-chk1",
                  type: "checklist",
                  items: [
                    "I have set up logging with Winston or Morgan",
                    "I monitor my application with PM2",
                    "I have a database backup strategy",
                    "I regularly audit and update dependencies"
                  ]
                }
              ]
            }
          ]
        },
        {
          id: "swdbd401-lo4-ic3",
          title: "Application Documentation",
          topics: [
            {
              id: "swdbd401-lo4-ic3-t1",
              title: "API Documentation with Swagger and Postman",
              blocks: [
                {
                  id: "swdbd401-lo4-ic3-t1-text1",
                  type: "text",
                  content: `## API Documentation

Good documentation is essential for maintainability and collaboration.

### Documentation Tools:
- **Swagger (OpenAPI)**: Auto-generated interactive API docs
- **Postman Collections**: Shareable API test/doc collections
- **JSDoc**: Code-level documentation from comments
- **GitHub**: Host and collaborate on documentation`
                },
                {
                  id: "swdbd401-lo4-ic3-t1-code1",
                  type: "code",
                  language: "javascript",
                  caption: "Setting up Swagger in Express",
                  code: `const swaggerJsDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const swaggerOptions = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Backend API',
      version: '1.0.0',
      description: 'SWDBD401 Backend Application API',
    },
    servers: [{ url: 'http://localhost:3000' }],
  },
  apis: ['./routes/*.js'],
};

const swaggerDocs = swaggerJsDoc(swaggerOptions);
app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocs));
// Visit http://localhost:3000/api-docs to view documentation`
                },
                {
                  id: "swdbd401-lo4-ic3-t1-quiz1",
                  type: "quiz",
                  questions: [{
                    id: "swdbd401-lo4-ic3-t1-quiz1-q1",
                    questionType: "mcq",
                    question: "Which tool provides an interactive UI for exploring and testing API documentation?",
                    options: ["PM2", "Swagger UI", "Nodemon", "bcrypt"],
                    correct: 1,
                    explanation: "Swagger UI generates an interactive web interface from your OpenAPI specification where you can read and test your API directly."
                  }],
                },
                {
                  id: "swdbd401-lo4-ic3-t1-chk1",
                  type: "checklist",
                  items: [
                    "I have documented all API endpoints",
                    "I have set up Swagger or Postman documentation",
                    "I have added code comments using JSDoc format",
                    "I have published documentation on GitHub"
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
};

MODULES.push(swdbd401);

// ─── All other curriculum modules ─────────────────────────────────────────────
// These are auto-registered with proper slugs, codes and track names.
// The LearnModuleReader fetches live content from /api/module/[slug] (DB first).
// The buildFallbackModule() generates a placeholder until a trainer adds content.

// Helper to build a module entry quickly
function reg(
  id: string, code: string, title: string, tier: string,
  trackName: string, xpReward = 60, estimatedMinutes = 120
): LearnModule {
  const existing = MODULES.find(m => m.slug === id);
  if (existing) return existing; // skip if already registered (swdbd401)
  return buildFallbackModule(id); // content loaded from DB at runtime
}

// ── LEVEL 3 ──
const l3Modules = [
  { id: "l3-web-dev", code: "L3-WEB", title: "Web Development", tier: "l3", trackName: "Web Development", xp: 80 },
  { id: "l3-js", code: "L3-JS", title: "JavaScript Fundamentals", tier: "l3", trackName: "JavaScript Fundamentals", xp: 80 },
  { id: "l3-game-vue", code: "L3-GAME", title: "Game Development in Vue Framework", tier: "l3", trackName: "Game Development in Vue Framework", xp: 80 },
  { id: "l3-ux-design", code: "L3-UX", title: "UX Design", tier: "l3", trackName: "UX Design", xp: 60 },
  { id: "l3-vcs", code: "L3-VCS", title: "Version Control", tier: "l3", trackName: "Version Control", xp: 50 },
  { id: "l3-reqs", code: "L3-REQS", title: "Software Project Requirements Analysis", tier: "l3", trackName: "Software Project Requirements Analysis", xp: 60 },
  { id: "l3-graphic-design", code: "L3-GD", title: "Apply Graphic Design", tier: "l3", trackName: "Apply Graphic Design", xp: 50 },
  { id: "l3-algebra", code: "GENFT302", title: "Fundamental Algebra and Trigonometry", tier: "l3", trackName: "Fundamental Algebra and Trigonometry", xp: 50 },
  { id: "l3-physics", code: "GENGP302", title: "Apply General Physics", tier: "l3", trackName: "Apply General Physics", xp: 50 },
  { id: "l3-entre", code: "CCMBC302", title: "Entrepreneurship", tier: "l3", trackName: "Entrepreneurship (L3)", xp: 40 },
  { id: "l3-ict", code: "CCMCL302", title: "ICT", tier: "l3", trackName: "ICT (L3)", xp: 40 },
  { id: "l3-citizen", code: "CCMCZ301", title: "Citizenship", tier: "l3", trackName: "Citizenship (L3)", xp: 40 },
  { id: "l3-english", code: "CCMEN302", title: "English", tier: "l3", trackName: "English (L3)", xp: 40 },
  { id: "l3-french", code: "CCMFT302", title: "Français", tier: "l3", trackName: "Français (L3)", xp: 40 },
  { id: "l3-she", code: "CCMHE303", title: "Safety, Health and Environment", tier: "l3", trackName: "Safety, Health and Environment (L3)", xp: 40 },
  { id: "l3-kinya", code: "CCMKN302", title: "Ikinyarwanda Kiboneye", tier: "l3", trackName: "Ikinyarwanda Kiboneye (L3)", xp: 40 },
  { id: "l3-ol", code: "CCMOL302", title: "Occupation and Learning Process", tier: "l3", trackName: "Occupation and Learning Process (L3)", xp: 40 },
  { id: "l3-iap", code: "ICTIA302", title: "Industrial Attachment Program", tier: "l3", trackName: "Industrial Attachment Program (L3)", xp: 50 },
];

// ── LEVEL 4 (other than swdbd401 already registered) ──
const l4Modules = [
  { id: "l4-backend-design", code: "SWDBS401", title: "Backend System Design", tier: "l4", trackName: "Backend System Design", xp: 80 },
  { id: "l4-dsa", code: "SWDDA401", title: "Data Structure and Algorithm Fundamentals", tier: "l4", trackName: "Data Structure and Algorithm Fundamentals", xp: 100 },
  { id: "l4-db-dev", code: "SWDDD401", title: "Database Development", tier: "l4", trackName: "Database Development", xp: 100 },
  { id: "l4-php", code: "SWDPP401", title: "PHP Programming", tier: "l4", trackName: "PHP Programming", xp: 80 },
  { id: "l4-windows-server", code: "SWDWS401", title: "Windows Server Administration", tier: "l4", trackName: "Windows Server Administration", xp: 80 },
  { id: "l4-networking", code: "GENBN401", title: "Basics of Networking", tier: "l4", trackName: "Basics of Networking", xp: 60 },
  { id: "l4-math", code: "GENFA402", title: "Apply Fundamental Mathematics Analysis", tier: "l4", trackName: "Apply Fundamental Mathematics Analysis", xp: 50 },
  { id: "l4-mechanics", code: "GENMP402", title: "Apply Mechanics and Properties of Matter", tier: "l4", trackName: "Apply Mechanics and Properties of Matter", xp: 50 },
  { id: "l4-entre", code: "CCMBP402", title: "Entrepreneurship (L4)", tier: "l4", trackName: "Entrepreneurship (L4)", xp: 40 },
  { id: "l4-ict", code: "CCMCS402", title: "ICT (L4)", tier: "l4", trackName: "ICT (L4)", xp: 40 },
  { id: "l4-english", code: "CCMEN402", title: "English (L4)", tier: "l4", trackName: "English (L4)", xp: 40 },
  { id: "l4-french", code: "CCMFT402", title: "Français (L4)", tier: "l4", trackName: "Français (L4)", xp: 40 },
  { id: "l4-iap", code: "CCMIA402", title: "Industrial Attachment Program (IAP)", tier: "l4", trackName: "Industrial Attachment Program (L4)", xp: 50 },
  { id: "l4-kinya", code: "CCMKN402", title: "Ikinyarwanda (L4)", tier: "l4", trackName: "Ikinyarwanda (L4)", xp: 40 },
  { id: "l4-citizen", code: "CMCZ401", title: "Citizenship (L4)", tier: "l4", trackName: "Citizenship (L4)", xp: 40 },
];

// ── LEVEL 5 ──
const l5Modules = [
  { id: "l5-blockchain", code: "SWDBF501", title: "Blockchain Fundamentals", tier: "l5", trackName: "Blockchain Fundamentals", xp: 100 },
  { id: "l5-frontend", code: "SWDFA501", title: "Front-End App Development with React.JS", tier: "l5", trackName: "Front-End App Development with React.JS", xp: 100 },
  { id: "l5-integrate", code: "SWDIA502", title: "Integrate the Workplace", tier: "l5", trackName: "Integrate the Workplace", xp: 60 },
  { id: "l5-mobile", code: "SWDMA501", title: "Mobile App Development", tier: "l5", trackName: "Mobile App Development", xp: 100 },
  { id: "l5-ml", code: "SWDML501", title: "Machine Learning Application", tier: "l5", trackName: "Machine Learning Application", xp: 120 },
  { id: "l5-nosql", code: "SWDND501", title: "NoSQL Database Development", tier: "l5", trackName: "NoSQL Database Development", xp: 80 },
  { id: "l5-devops", code: "SWDOT501", title: "DevOps Application", tier: "l5", trackName: "DevOps Application", xp: 100 },
  { id: "l5-math-stats", code: "GENAP502", title: "Mathematical Analysis, Statistics and Probability", tier: "l5", trackName: "Mathematical Analysis, Statistics and Probability", xp: 60 },
  { id: "l5-dynamics", code: "GENDW502", title: "Apply Dynamics and Waves", tier: "l5", trackName: "Apply Dynamics and Waves", xp: 50 },
  { id: "l5-python", code: "GENPP501", title: "Python Programming", tier: "l5", trackName: "Python Programming", xp: 80 },
  { id: "l5-qa", code: "GENQA501", title: "Quality Assurance", tier: "l5", trackName: "Quality Assurance", xp: 60 },
  { id: "l5-business", code: "CCMBO502", title: "Organise a Business (L5)", tier: "l5", trackName: "Organise a Business (L5)", xp: 40 },
  { id: "l5-citizen", code: "CCMCZ501", title: "Civic Attitudes & Harmony (L5)", tier: "l5", trackName: "Civic Attitudes & Harmony (L5)", xp: 40 },
  { id: "l5-english", code: "CCMEN502", title: "English at Workplace (L5)", tier: "l5", trackName: "English at Workplace (L5)", xp: 40 },
  { id: "l5-french", code: "CCMFT502", title: "Français (L5)", tier: "l5", trackName: "Français (L5)", xp: 40 },
  { id: "l5-ict", code: "CCMIW502", title: "ICT at Workplace (L5)", tier: "l5", trackName: "ICT at Workplace (L5)", xp: 40 },
  { id: "l5-kiswahili", code: "CCMKK502", title: "Kiswahili (L5)", tier: "l5", trackName: "Kiswahili (L5)", xp: 40 },
  { id: "l5-kinya", code: "CCMKN502", title: "Ikinyarwanda k'intyoza (L5)", tier: "l5", trackName: "Ikinyarwanda k'intyoza (L5)", xp: 40 },
  { id: "l5-ethics", code: "CCMPE502", title: "Professional & Multicultural Ethics (L5)", tier: "l5", trackName: "Professional & Multicultural Ethics (L5)", xp: 40 },
];

// ─── Build LearnModule from curriculumContent + derive DB-matching topic IDs ──
//
// Topic IDs are derived as: seed-node-seed-track-{trackSlug}-0-t{n}
// This matches exactly what seed-content.ts writes to the DB.
//
import { getCurriculumContent } from "@/lib/curriculumContent";

function trackSlugFromName(trackName: string): string {
  return trackName.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

function buildModuleFromCurriculum(meta: {
  id: string; code: string; title: string; tier: string;
  trackName: string; xp: number;
}): LearnModule {
  const curriculum = getCurriculumContent(meta.trackName);
  const tSlug = trackSlugFromName(meta.trackName);
  const nodeId = `seed-node-seed-track-${tSlug}-0`;

  if (!curriculum) {
    return {
      ...buildFallbackModule(meta.id),
      moduleCode: meta.code,
      title: meta.title,
      tier: meta.tier,
      trackName: meta.trackName,
      xpReward: meta.xp,
    };
  }

  // Build outcomes/ICs/topics from curriculumContent, deriving nodeId-based topic IDs
  let flatTopicIndex = 0;
  const outcomes: LearningOutcome[] = curriculum.learningOutcomes.map((lo, loIdx) => ({
    number: loIdx + 1,
    title: lo.title,
    learningHours: lo.hours,
    indicativeContents: lo.topics.map((topic, topicIdx) => ({
      id: `${meta.id}-lo${loIdx + 1}-ic${topicIdx + 1}`,
      title: topic.title,
      topics: topic.subtopics.map((sub) => {
        // This ID must match what seed-content.ts wrote: nodeId + "-t" + (n)
        const n = ++flatTopicIndex;
        return {
          id: `${nodeId}-t${n}`,
          title: sub.title,
          description: sub.items?.join(" · ").slice(0, 100),
          items: sub.items || [], // Store items for student sidebar display
          blocks: [] as LearnBlock[], // populated at runtime from DB
        };
      }),
    })),
  }));

  return {
    slug: meta.id,
    moduleCode: meta.code,
    title: meta.title,
    tier: meta.tier,
    trackName: meta.trackName,
    xpReward: meta.xp,
    estimatedMinutes: curriculum.totalHours * 4,
    description: curriculum.purpose,
    outcomes,
  };
}

// Register all non-swdbd401 modules with curriculum-derived structure
for (const m of [...l3Modules, ...l4Modules, ...l5Modules]) {
  const mod = buildModuleFromCurriculum(m);
  MODULES.push(mod);
  // Also register the long-form slug that PassportClient generates
  // e.g. "l5-specific-modules-swdml501-machine-learning-application"
  // so both URLs resolve to the same module
  const altSlugs: string[] = [
    `l5-specific-modules-${m.code.toLowerCase()}-${m.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    `l4-specific-modules-${m.code.toLowerCase()}-${m.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    `l3-specific-modules-${m.code.toLowerCase()}-${m.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    `l5-general-modules-${m.code.toLowerCase()}-${m.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    `l4-general-modules-${m.code.toLowerCase()}-${m.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
    `l3-general-modules-${m.code.toLowerCase()}-${m.title.toLowerCase().replace(/[^a-z0-9]+/g, "-")}`,
  ].filter(s => s !== m.id);
  for (const alt of altSlugs) {
    if (!MODULES.find(x => x.slug === alt)) {
      MODULES.push({ ...mod, slug: alt });
    }
  }
}

// ─── Helper: get all topics flat for a module ─────────────────────────────────

export function getAllTopics(module: LearnModule): LearnTopic[] {
  return module.outcomes.flatMap((o) =>
    o.indicativeContents.flatMap((ic) => ic.topics)
  );
}

// ─── Helper: count all blocks across module ───────────────────────────────────

export function countAllBlocks(module: LearnModule): number {
  return getAllTopics(module).reduce((sum, t) => sum + t.blocks.length, 0);
}

// ─── Smart Fallback Generator ─────────────────────────────────────────────────

function buildFallbackModule(slug: string): LearnModule {
  const parts = slug.split("-");
  const levelStr = (parts[0] ?? "l4").toUpperCase();
  const titleWords = parts
    .slice(2)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
  const cleanTitle = titleWords.length > 0 ? titleWords : "Curriculum Module";
  const codeMatch = cleanTitle.match(/^([A-Z0-9]+)/);
  const moduleCode = codeMatch ? codeMatch[1] : levelStr;

  return {
    slug,
    moduleCode,
    title: cleanTitle,
    tier: parts[0] ?? "l4",
    trackName: `${levelStr} — Curriculum Module`,
    xpReward: 50,
    estimatedMinutes: 60,
    description: `Official Rwanda TVET curriculum module: ${cleanTitle}.`,
    outcomes: [
      {
        number: 1,
        title: `Analyze Foundations of ${cleanTitle}`,
        learningHours: 15,
        indicativeContents: [
          {
            id: `${slug}-lo1-ic1`,
            title: "Core Concepts",
            topics: [
              {
                id: `${slug}-lo1-ic1-t1`,
                title: "Topic 1.1: Core Concepts & Principles",
                blocks: [
                  {
                    id: `${slug}-lo1-ic1-t1-text1`,
                    type: "text",
                    content: `## Foundations of ${cleanTitle}\n\nWelcome to this TVET Rwanda curriculum module. Study the learning outcomes and complete each topic.`,
                  },
                  {
                    id: `${slug}-lo1-ic1-t1-chk1`,
                    type: "checklist",
                    items: [
                      "I have reviewed the core concepts",
                      "I understand the practical requirements",
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function getLearnModule(slug: string): LearnModule {
  const explicit = MODULES.find((m) => m.slug === slug);
  if (explicit) return explicit;

  const normalizedSlug = slug.toLowerCase();
  const looseMatch = MODULES.find(
    (m) =>
      normalizedSlug.includes(m.moduleCode.toLowerCase()) ||
      m.slug.includes(normalizedSlug)
  );
  if (looseMatch) return looseMatch;

  return buildFallbackModule(slug);
}

export default MODULES;
